---
version: "3.8"
services:

  postgres:
    image: postgres:15-alpine
    container_name: chatfaq_postgres
    hostname: chatfaq_postgres
    volumes:
      - chatfaq_db_data:/var/lib/postgresql/data/
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata/
    networks:
      - chatfaq_db_net

  back:
    build:
      context: back
      dockerfile: Dockerfile
    image: chatfaq_back
    container_name: chatfaq_back
    hostname: chatfaq_back
    depends_on:
      - postgres
    ports:
      - 8000:8000
    networks:
      - default
      - chatfaq_db_net
      - chatfaq_back_net
      - chatfaq_state_machine_net

  worker:
    build:
      context: worker
      dockerfile: Dockerfile
    image: chatfaq_worker
    container_name: chatfaq_worker
    hostname: chatfaq_worker
    depends_on:
      - back
    networks:
      - chatfaq_back_net
      - chatfaq_db_net

  state-machine:
    build:
      context: sdk
      dockerfile: Dockerfile
    image: chatfaq_fsm
    container_name: chatfaq_fsm
    hostname: chatfaq_fsm
    depends_on:
      - back
    networks:
      - chatfaq_state_machine_net

  widget:
    build:
      context: widget
      dockerfile: Dockerfile
    image: chatfaq_widget
    container_name: chatfaq_widget
    depends_on:
      - back
    ports:
      - 3000:3000
    networks:
      - default
      - chatfaq_back_net

volumes:
  chatfaq_db_data:

networks:
  chatfaq_db_net:  # postgres, back
  chatfaq_back_net:  # back, widget
  chatfaq_state_machine_net:  # back, state-machine

