---
# Inject environment variables

version: "3.8"
services:

  postgres:
    env_file:
      - "back/.env"

  back:
    env_file:
      - "back/.env"

  chatfaq-retrieval-server:
    env_file:
      - "chatfaq-retrieval-server/.env"

  widget:
    env_file:
      - "widget/.env"

  state-machine:
    env_file:
      - "sdk/.env"
