[tool.poetry]
name = "chatfaq"
version = "0.1.0"
description = ""
authors = ["With Technology"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
myst-parser = "^0.18.1"
django = "^4.1.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
