version: "2.1"
services:
    back:
        build: .
        ports:
            - 8000:8000
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - chatfaq
        volumes:
            - ./:/var/apps/back
        env_file:
            - .env_docker
    postgres:
        image: postgres:15
        networks:
            - chatfaq
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=super
            - POSTGRES_DB=chatfaq
        healthcheck:
            test: if psql -U postgres -lqt | cut -d \| -f 1 | grep -w chatfaq; then exit 0; else exit 1; fi
            interval: 5s
            timeout: 5s
            retries: 5
volumes:
    pgdata:
networks:
    chatfaq:
        driver: bridge
