[tool.poetry]
name = "chat-rag"
version = "0.1.27"
description = ""
authors = ["Diego Peláez Paquico <diego.pelaez@with-madrid.com>"]
readme = "README.md"
packages = [{ include = "chat_rag" }]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "1.23.5"
pandas = "1.4.4"
transformers = "^4.29.2"
sentence-transformers = "^2.2.2"
pyarrow = "^12.0.0"
python-dotenv = "^0.21.0"
torch = [
    { version = "^2.0.1", source = "torch" },
]
ctransformers = "^0.2.10"
tqdm = "^4.65.0"
einops = "^0.6.1"
openai = "^0.27.8"
accelerate = "^0.21.0"
unstructured = {extras = ["pdf"], version = "^0.10.12"}
guidance = "^0.0.64"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "test"
url = "https://test.pypi.org/simple/"
secondary = true

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"
