version: '3'
services:
  ray-head:
    image: rayproject/ray:latest-py310 
    command: /bin/bash -c "ray start --head --port ${RAY_ADDRESS_PORT} --dashboard-host 0.0.0.0 --block"
    env_file:
      - .env
    ports:
      - ${RAY_ADDRESS_PORT}:${RAY_ADDRESS_PORT}
      - ${RAY_DASHBOARD_PORT}:${RAY_DASHBOARD_PORT}
      - ${RAY_HEAD_NODE_PORT}:${RAY_HEAD_NODE_PORT}
    networks:
      - ray_net

  ray-indexing-worker-1:
    image: rayproject/ray-ml:latest-py310-gpu
    command: ["ray", "start", "--address=ray-head:${RAY_ADDRESS_PORT}", "--resources={\"indexing_node\": 5}", "--block"]
    env_file:
      - .env
    depends_on:
      - ray-head
    deploy:
      mode: replicated
      replicas: ${INDEXING_WORKERS}
      resources:
        limits:
          cpus: ${INDEXING_WORKER_CPU}
          memory: 2G
    networks:
      - ray_net

  # ray-pdf-parsing-worker-1:
  #   image: rayproject/ray-ml:latest-py310-gpu
  #   command: ["ray", "start", "--address=ray-head:6379", "--resources={\"pdf_parsing_node\": 5}"]
  #   depends_on:
  #     - ray-head


networks:
  ray_net:
    ipam:
      driver: default
      config:
        - subnet: 172.63.0.0/16