---
name: Deploy ChatFAQ

on:
  push:
    paths:
      - "back/**"
      - "widget/**"
      - "sdk/**"
      - "Dogefile"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Upload manifest
        uses: WithAgency/dogeops-action@v1
        with:
          api_url: ${{ vars.DOGEOPS_API_URL }}
          api_key: ${{ secrets.DOGEOPS_API_KEY }}
